package main

import (
	"bufio"
	"encoding/json"
	"io"
	"sort"
	"strings"
)

// writeStreamCell writes one table row to bw.
func writeStreamCell(bw *bufio.Writer, content string, wasExpanded bool) {
	bw.WriteString(`{"content":`)
	b, _ := json.Marshal(content)
	bw.Write(b)
	if wasExpanded {
		bw.WriteString(`,"wasExpanded":true}`)
	} else {
		bw.WriteString(`,"wasExpanded":false}`)
	}
}

// expandSpansToJSON streams the expanded cell grid as JSON directly to w.
func expandSpansToJSON(rawRows [][]rawCell, w io.Writer) error {
	if len(rawRows) == 0 {
		_, err := io.WriteString(w, "[]")
		return err
	}

	maxRawCols := 0
	for _, row := range rawRows {
		if len(row) > maxRawCols {
			maxRawCols = len(row)
		}
	}

	bw := bufio.NewWriterSize(w, 64*1024)

	// fast path: no spans present, just write rows
	simple := true
outer:
	for _, row := range rawRows {
		for _, c := range row {
			colspan := c.colspan
			if colspan > maxRawCols {
				colspan = 1
			}
			if colspan != 1 || c.rowspan != 1 {
				simple = false
				break outer
			}
		}
	}

	bw.WriteByte('[')

	if simple {
		for ri, row := range rawRows {
			if ri > 0 {
				bw.WriteByte(',')
			}
			bw.WriteByte('[')
			for ci, c := range row {
				if ci > 0 {
					bw.WriteByte(',')
				}
				writeStreamCell(bw, c.content, false)
			}
			bw.WriteByte(']')

			if err := bw.Flush(); err != nil {
				return err
			}
		}
	} else {
		// Slow path: at least one cell has a colspan or rowspan > 1.
		type pend struct {
			content string
			rem     int // remaining rows to fill, counting down
		}
		var pending map[int]pend

		for ri, rawRow := range rawRows {
			if ri > 0 {
				bw.WriteByte(',')
			}
			bw.WriteByte('[')

			firstCell := true
			emitCell := func(content string, wasExpanded bool) {
				if !firstCell {
					bw.WriteByte(',')
				}
				firstCell = false
				writeStreamCell(bw, content, wasExpanded)
			}

			outputColumn, rawColumnIndex := 0, 0
			for rawColumnIndex < len(rawRow) || len(pending) != 0 {
				for p, ok := pending[outputColumn]; ok; p, ok = pending[outputColumn] {
					emitCell(p.content, true)
					if p.rem > 1 {
						pending[outputColumn] = pend{p.content, p.rem - 1}
					} else {
						delete(pending, outputColumn)
					}
					outputColumn++
				}
				if rawColumnIndex >= len(rawRow) {
					break
				}

				rawCell := rawRow[rawColumnIndex]
				rawColumnIndex++
				colspan := rawCell.colspan
				if colspan > maxRawCols {
					colspan = 1 // colspan wider than the table, treat as 1
				}
				rowspan := rawCell.rowspan
				if rowspan < 1 { // 0 or negative rowspan, shouldn't happen
					rowspan = 1
				}
				if rowspan > len(rawRows) {
					rowspan = 1 // rowspan taller than the table, treat as 1
				}

				// Emit the original (non-expanded) cell and register a carry if its rowspan extends into later rows.
				emitCell(rawCell.content, false)
				if rowspan > 1 {
					if pending == nil {
						pending = make(map[int]pend)
					}
					pending[outputColumn] = pend{rawCell.content, rowspan - 1}
				}
				outputColumn++

				// Emit the extra columns generated by colspan, draining any pending carries that occupy those columns first.
				for k := 1; k < colspan; k++ {
					for p, ok := pending[outputColumn]; ok; p, ok = pending[outputColumn] {
						emitCell(p.content, true)
						if p.rem > 1 {
							pending[outputColumn] = pend{p.content, p.rem - 1}
						} else {
							delete(pending, outputColumn)
						}
						outputColumn++
					}
					emitCell(rawCell.content, true)
					if rowspan > 1 {
						if pending == nil {
							pending = make(map[int]pend)
						}
						pending[outputColumn] = pend{rawCell.content, rowspan - 1}
					}
					outputColumn++
				}
			}

			bw.WriteByte(']')

			if err := bw.Flush(); err != nil {
				return err
			}
		}

		// Emit synthetic rows for any rowspans that extend beyond the last explicit row
		for len(pending) != 0 {
			cols := make([]int, 0, len(pending))
			for c := range pending {
				cols = append(cols, c)
			}
			sort.Ints(cols)

			bw.WriteByte(',')
			bw.WriteByte('[')
			firstCell := true
			for _, c := range cols {
				p := pending[c]
				if !firstCell {
					bw.WriteByte(',')
				}
				firstCell = false
				writeStreamCell(bw, p.content, true)

				if p.rem > 1 {
					pending[c] = pend{p.content, p.rem - 1}
				} else {
					delete(pending, c)
				}
			}
			bw.WriteByte(']')

			if err := bw.Flush(); err != nil {
				return err
			}
		}
	}

	bw.WriteByte(']')
	if err := bw.Flush(); err != nil {
		return err
	}

	return nil
}

// tableCellsToJSON parses text into raw rows and then calls expandSpansToJSON;
func tableCellsToJSON(text string, w io.Writer) error {
	if text == "" {
		_, err := io.WriteString(w, "null")
		return err
	}
	var rawRows [][]rawCell
	if strings.HasPrefix(strings.TrimSpace(text), "{|") {
		rawRows = parseWikiRawRows(text)
	} else {
		rawRows = htmlToRawRows(text)
	}
	if rawRows == nil {
		_, err := io.WriteString(w, "null")
		return err
	}
	return expandSpansToJSON(rawRows, w)
}
